language: node_js
node_js: 10.15.2
script: yarn build
cache: yarn
branches:
  only:
  - master
  - develop
  - "/feature-.+/"
  - "/release-.+/"
  - "/fix-.+/"
after_success: test $TRAVIS_BRANCH = "master" && yarn release
deploy:
  provider: heroku
  api_key:
    secure: A8SSZt7dAL7dezMhlkCko6P+UQy5BcAuXe3xd/fcmvkAxbicLWZrCYcUyknRr7zF4zgCVnWNQnbLSynXYAqin5a0RYqscf8Cpnjw3sQvEJPMrkK1XsxLCwYrG658++RegdauL8gK2+OcoshMnmy239VUvXIh8dbBfObzRxn538rT1GD7P26g7sCuEa/01NWWIUwv2cCkI39tX8r6rPeuEolKo+Q8O2Wt7dWuYHdJ2/of//t/q1eikUf09fXFCpoWA9Tn1fKLrzfUf820WYW9hu72RSqzYDIWvGyLAbHFzRjgWhif6to0PkwG1t0l/ChcPc6xKBhvz7AkiBrVjWG0k1N9x916q7XMnm6AK3bfwmDXWfg82mUh4aoxlE2uSRIuEiXNWXuVnn9q0b4wdE6GO/lNQsQWNoEao7hYbEqw3Ya6sW/Dree5HUg6N7c7ha4lSpNf6A3Kq7bDwtoR+w3CvZEmMP1fmALEWnS/oMqldMvSvZpO3A0RnXecFArqmA2+HP56zZcxvZprmgEVlTOUP3kk+NwHSCZLUF4M27AyNHsns4TmLCE34Q3BK5pLisPL4QxiXIPIRBqIRO0CWPC6RW9hVxWBy6izGaVuxq8NM6dtugjmL0NXd04I9SmFuxo6yNjSg+j/+F5GnYQYZv2m/efek9ytYOnneuXWFmgU3rg=
  on: master
